on:
  release:
    types: [published]

name: Update release

jobs:
  update_release:
    name: Update release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v1
      - name: handle-release-notes
        uses: principalstudio/handle-release-notes@v1
        with:
          main-branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: prepare-version-number-var
        id: prep
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo ::set-output name=version::${VERSION}
      - name: update-package-version
        uses: MerthinTechnologies/edit-json-action@v1
        with:
          filename: './package.json'
          key: 'version'
          value: ${{ steps.prep.outputs.version }}
      - name: update-package-lock-version
        uses: MerthinTechnologies/edit-json-action@v1
        with:
          filename: './package-lock.json'
          key: 'version'
          value: ${{ steps.prep.outputs.version }}
